### ISSUE TITLE
User story 1 - User can see the homepage of the application

### ISSUE THREAD

**Issue by ekachernova** [ekachernova/digital-wardrobe-application#1]
**Value:**

As a User I want to be able:

- to see Homepage of the application
- to see the button by using that I can start creating my first digital wardrobe

**Description:**

<img src="https://github.com/ekachernova/digital-wardrobe-application/assets/103756008/c2bcb1ee-e199-4386-95e1-96a52fd45f6a" width="250"/>

**Acceptance criteria:**

- [ ] header is displayed (without styling)
- [ ] footer is displayed  (without styling)
- [ ] button “create your digital wardrobe”  (without styling)

**Tasks:**

- [ ] set up new next.js project
- [ ] create basic jsx structure of the homepage
- [ ] add header basic structure
- [ ] add footer basic structure
