### ISSUE TITLE
User story 2 - User can add clothing items into the virtual wardrobe

### ISSUE THREAD

**Issue by ekachernova** [ekachernova/digital-wardrobe-application#2]
**Value**

As a user I want to be able to:

- add new clothing items to my virtual wardrobe
- see all added items in my wardrobe

**Description**

<img src="https://github.com/ekachernova/digital-wardrobe-application/assets/103756008/29772ad0-7ef6-45c1-8b9a-0f8b697b6871" width="250"/>
<img src="https://github.com/ekachernova/digital-wardrobe-application/assets/103756008/31751497-bfac-42ab-9e8e-38839482f3ba" width="250"/>

**Acceptance criteria**

- [x] by clicking on the "Create your wardrobe" button the user can see the new page with the wardrobe section
- [x] the wardrobe section (area) is displayed
- [x] the "+" button is displayed
- [x] the "+" button has an event listener in order to be able to add an clothing item (image) from your local machine
- [x] the added item is displayed in the wardrobe area

**Tasks**

- [x] implementation of the Routing between pages, check  the handouts examples;
- [x] create "Wardrobe" component to store all wardrobe items
- [x] create "AddButton" component to add new items into the Wardrobe
- [x] add styles to the components
- [x] test feature's implementation
