### ISSUE TITLE
User Story 3 - User can have a possibility to reuse (store) the uploaded data

### ISSUE THREAD

**Issue by ekachernova** [ekachernova/digital-wardrobe-application#3]
**Value**

As a user I want to be able to:

- reuse the uploaded images
- add new images into the wardrobe
- deleted images from the wardrobe

**Description**
<img src="https://github.com/ekachernova/digital-wardrobe-application/assets/103756008/5e4f9809-918d-4be5-9322-a66059ae876a" width="250">

**Acceptance criteria**

- [ ] by adding item into the gallery the user can see the added item in the wardrobe section
- [ ] the added item has been saved in Cloudinary
- [ ] the image URL is readable and can be reused for the backend flow
- [ ] the uploaded data can be stored in MongoDB

**Tasks**

- [ ] research about Cloudinary implementation
- [ ] understanding the backend flow
- [ ] design database
- [ ] setup Cloudinary
- [ ] test Cloudinary implementation using test folder
- [ ] research about how to connect Cloudinary and MongoDB
- [ ] setup MongoDB database
- [ ] connect the project with the database
