### ISSUE TITLE
User Story 4 - User can see the actual weather on the wardrobe section

### ISSUE THREAD

**Issue by ekachernova** [ekachernova/digital-wardrobe-application#5]
**Value**

As a user I want to be able to:

- see the actual weather when I open my wardrobe

**Description**
<img src= "https://github.com/ekachernova/digital-wardrobe-application/assets/103756008/4c8ad022-40ea-4d62-b377-1e6f13251013" width ="250">

**Acceptance criteria**

- [ ] user can see the actual wether on the wardrobe page
- [ ] user can see an image that shows the actual weather 
- [ ] user can see a disclaimer that describes the actual weather

**Tasks**

- [ ] recap how to use weather API
- [ ] create a Weather component
- [ ] create fetching weather using weather API
- [ ] testing functionality
