### ISSUE TITLE
User Story 5 - User can create simple outfits from the items in the wardrobe. Drag and drop playground #5

### ISSUE THREAD

**Issue by ekachernova** [ekachernova/digital-wardrobe-application#7]
**Value**

As a user I want to be able to:

- create outfits from the clothing items

**Description**
------

**Acceptance criteria**

- [ ] user can see playground where she can create outfits
- [ ] user can use drag and drop functionality for that

**Tasks**

- [ ] recap how to use drag and drop in React
- [ ] think about rendering
- [ ] create a Playground component
- [ ] add functions in order to implement drag and drop functionality
- [ ] test functionality
