### ISSUE TITLE
User Story 5 - User can see recommended items according to the weather conditions

### ISSUE THREAD

**Issue by ekachernova** [ekachernova/digital-wardrobe-application#8]
**Value**

As a user I want to be able to:

- see the items in the wardrobe that have been filtered according to the weather conditions

**Description**
<img src="https://github.com/ekachernova/digital-wardrobe-application/assets/103756008/129c7fc8-f1b1-4c8c-8e48-fdcab6247c7a" width="200"/>

**Acceptance criteria**

- [ ] user can see the wardrobe filtered according to the weather condition

**Tasks**

- [ ] thinking about rendering
- [ ] add field "season" to the form in order to use that for filtering
- [ ] add field "colour" to the form in order to use in future filtering
- [ ] create weatherFilteredWardrobe component
- [ ] create logic for filtering items
- [ ] test functionality
